/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    科技星球: THREE.Mesh
    ['科技星球-发光']: THREE.Mesh
  }
  materials: {
    科技星球: THREE.MeshPhysicalMaterial
    科技星球发光: THREE.MeshStandardMaterial
  }
}

export const Model = forwardRef<any>(
  (props: JSX.IntrinsicElements['group'], ref) => {
    const { nodes, materials } = useGLTF(
      '/planet2.glb'
    ) as unknown as GLTFResult
    return (
      <group {...props} dispose={null} ref={ref}>
        <directionalLight
          intensity={2}
          color="#ff63f7"
          position={[35.33, 10.09, 64.93]}
          rotation={[-0.15, 0.49, -3.07]}
        />
        <mesh
          geometry={nodes.科技星球.geometry}
          material={materials.科技星球}
          position={[0, -12.9, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes['科技星球-发光'].geometry}
          material={materials.科技星球发光}
          position={[0, -12.9, 0]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    )
  }
)

useGLTF.preload('/planet2.glb')
