/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    鲸鱼星球: THREE.Mesh
    ['鲸鱼星球-发光']: THREE.Mesh
  }
  materials: {
    鲸鱼星球: THREE.MeshPhysicalMaterial
    ['鲸鱼星球-发光']: THREE.MeshStandardMaterial
  }
}

export const Model = forwardRef<any>(
  (props: JSX.IntrinsicElements['group'], ref) => {
    const { nodes, materials } = useGLTF(
      '/planet1.glb'
    ) as unknown as GLTFResult
    return (
      <group {...props} dispose={null} ref={ref}>
        <directionalLight
          intensity={1}
          color="#9fe9ff"
          position={[37.79, 10.09, 63.52]}
          rotation={[-0.16, 0.53, -3.06]}
        />
        <mesh
          geometry={nodes.鲸鱼星球.geometry}
          material={materials.鲸鱼星球}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes['鲸鱼星球-发光'].geometry}
          material={materials['鲸鱼星球-发光']}
          position={[3.97, 1.34, -0.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    )
  }
)

useGLTF.preload('/planet1.glb')
